### ISSUE TITLE
httpbin returns something malicious

### ISSUE THREAD

**Issue by Dan-Mikkel** [spring-guides/gs-gateway#16] opened 2021-10-07 14:28 UTC
I am following this guide and when doing the curl command, i got this in response:
<html><head><title>Loading...</title></head><body><script type='text/javascript'>window.location.replace('http://httbin.org/get?js=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImV4cCI6MTYzMzYyMzkzMiwiaWF0IjoxNjMzNjE2NzMyLCJpc3MiOiJKb2tlbiIsImpzIjoxLCJqdGkiOiIycWxzYmdxN3Q1YTgwNGx1c3MwMnR0a2ciLCJuYmYiOjE2MzM2MTY3MzIsInRzIjoxNjMzNjE2NzMyMzY3NTc5fQ.ddhBr3IvtI8v1ItlI3nboJR0Ng0K2tu72U97Uboa0i8&sid=6dd0a6b8-277a-11ec-a668-5f460581a7c8');</script></body></html>% 

In the browser, it redirects me to shady sites. Is there something with httpbin, my machine or something else?

**Comment by robertmcnees** [comment] 2024-05-08 11:02
Hi @Dan-Mikkel. Sorry for the delayed response. That does not look good! I went through the guide myself, both by running the application from the `complete` folder as well as starting in the `initial` folder and building it up according to the guide. Neither time did I get anything like what you sent.

Due to the time since the issue was filed and my ability to reproduce, I'm going to close the issue. If this is still something that you are facing, please reply to the issue.

**Closed as completed by robertmcnees** 2024-05-08 11:02 UTC
